Navbar
wolox-training/ic-angular pull request #7
Opened 2019-04-03 21:18 UTC by idcuadrowolox

## Summary
- Navbar

## Screenshot

![ezgif com-resize](https://user-images.githubusercontent.com/49001977/55513732-12794d00-562c-11e9-9241-31d6538f3283.gif)

## Trello Card
https://trello.com/c/x0TrT3cD/13-navbar

2019-04-03 21:41 UTC, henryzarza requested changes
Update this branch with master

2019-04-03 21:41 UTC, henryzarza commented on maquetado/index.html
> +  <div class="nav-bar">
For keeping a good structure, change this for: `nav` tag

2019-04-03 21:41 UTC, henryzarza commented on maquetado/index.html
> +    <img class="nav-bar-logo" src="assets/wolox_logo.svg" alt="Wolox Logo"></img>
The `img` doesn't have closed

2019-04-03 21:41 UTC, henryzarza commented on maquetado/scss/_navbar.scss
> +@import 'colors';
Do you need import this?

2019-04-03 21:41 UTC, henryzarza commented on maquetado/scss/_navbar.scss
> +@import 'variables';
The same question here

2019-04-03 21:41 UTC, henryzarza commented on maquetado/scss/_navbar.scss
> +  z-index: 9999;
Isn't a good practice to assign z-index values too high because the maintenance is very difficult, so change it for `1`

2019-04-03 21:41 UTC, henryzarza commented on maquetado/scss/_navbar.scss
> +.nav-bar {
I think that is necessary a `box-shadow`. What do you think? 😉

2019-04-03 21:41 UTC, henryzarza commented on maquetado/scss/_navbar.scss
> +    margin-left: auto;
Is necessary?

2019-04-03 21:53 UTC, idcuadrowolox commented on maquetado/scss/_navbar.scss
> +.nav-bar {
I'm sorry, I didn't see it jajajaja

2019-04-04 12:13 UTC, henryzarza requested changes

2019-04-04 12:13 UTC, henryzarza commented on maquetado/scss/_colors.scss
> +$light_gray: #CCC;
Change by: `$light-gray`

2019-04-04 17:00 UTC, henryzarza approved these changes

2019-04-04 17:15 UTC, merged